### ISSUE TITLE
There is no recipe for c++

### ISSUE THREAD

**Issue by ronisbr** [renzmann/treesit-auto#14]
When I open a C++ file, it shows the message:

```
There is no recipe for c++, do you want to build it interactively?
```

Even after building the C++ grammar, tree-sitter does not work. I think the problem is related with the language name `c++` instead of `cpp`.

**Comment by renzmann** [comment]
Ah yeah, https://github.com/renzmann/treesit-auto/blob/40ccc0dc97a3b13f4497a310264a9723baef920e/treesit-auto.el#L82

Should be 
```elisp
    (c++ "https://github.com/tree-sitter/tree-sitter-cpp")
```

However, there's another issue when I compile this:

```
⛔ Warning (treesit): The installed language grammar for c++ cannot be located or has problems (symbol-error): /home/robb/.emacs.d/tree-sitter/libtree-sitter-c++.so: undefined symbol: tree_sitter_c++
```

I bet it's because `scanner.cc` is separate in the src directory, but need to look into how to pass that information to `treesit-install-language-grammar`
