### ISSUE TITLE
Here is a swift tree-sitter that works great.

### ISSUE THREAD

**Issue by konrad1977** [renzmann/treesit-auto#15]
This is the one I use I think it performs great for swift.
https://gitlab.com/woolsweater/tree-sitter-swifter

Would be nice if it could be added? (or if I can add it my-self somehow).

**Comment by renzmann** [comment]
Happy to include it!

> if I can add it my-self somehow

In case there are any questions around this, a simple [fork + pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) works if the contributor tag is important to you.  Otherwise I'll go ahead and just add it in here: https://github.com/renzmann/treesit-auto/blob/40ccc0dc97a3b13f4497a310264a9723baef920e/treesit-auto.el#L99-L105

**Comment by konrad1977** [comment]
You can just go a head and add it. The tag is not important =)

**Comment by renzmann** [comment]
The link in the original post doesn't include a `parser.c`, so it's not compatible with the Emacs `treesit` library.  What I'll do instead, though, is include the [official tree-sitter](https://github.com/tree-sitter/tree-sitter-swift) version.

**Comment by konrad1977** [comment]
This ones also works. Its a bit slow though. https://github.com/alex-pinkus/tree-sitter-swift

**Comment by konrad1977** [comment]
A bit off topic. But when using the built in treesit (29.x) where do you put your grammars/highlight file?

**Comment by renzmann** [comment]
> This ones also works. Its a bit slow though. https://github.com/alex-pinkus/tree-sitter-swift

I took a look there too, but don't see a `parser.c` there either, so it still won't work with Emacs' `treesit-install-langauge-grammar`.

> ...when using the built in treesit (29.x) where do you put your grammars/highlight file?

By default, Emacs uses `~/.emacs.d/tree-sitter` as the install location for the libraries.  However, any location on `treesit-extra-load-path` will work.  See the "Parsing Program Source" section in the "elisp" manual for all the goodies: `C-h R elisp RET m Parsing Program Source RET`
