### ISSUE TITLE
[feature] Provide customizable variable for directory containing compiled grammars

### ISSUE THREAD

**Issue by ktetzlaff** [renzmann/treesit-auto#18]
Currently, compiled tree-sitter grammars are stored in the directory `<user-emacs-directory>/tree-sitter.` It would be nice if the location could be customized.

**Comment by renzmann** [comment]
I agree that would be nice, but I also don't think it would be in scope for this project.  At least for now, [treesit-install-language-grammar](https://github.com/emacs-mirror/emacs/blob/ac7ec87a7a0db887e4ae7fe9005aea517958b778/lisp/treesit.el#L2865-L2867) doesn't let us pick a place to install, since it's always passing nil to `out-dir`, and I'd rather not try to rely on an internal function like `treesit--install-langauge-grammar-1`, so we might have more luck submitting a patch to `treesit.el` instead of here.  If that gets accepted upstream, I'd consider adding it here, but that would increase the already strong requirement we have on compatible Emacs versions.

**Comment by renzmann** [comment]
That said, you are free to customize `treesit-extra-load-path` and place your grammars there, once compiled.

**Comment by ktetzlaff** [comment]
> At least for now, [treesit-install-language-grammar](https://github.com/emacs-mirror/emacs/blob/ac7ec87a7a0db887e4ae7fe9005aea517958b778/lisp/treesit.el#L2865-L2867) doesn't let us pick a place to install, since it's always passing nil to `out-dir`, and I'd rather not try to rely on an internal function like `treesit--install-langauge-grammar-1`, so we might have more luck submitting a patch to `treesit.el` instead of here.
Oh, ok. I didn't notice that you're just using a function defined by upstream. In this case I agree. The functionality should be provided by `treesit.el`. In the meantime I will probably use an :after advice.

Thanks for working on this!

**Comment by Roger-Roger-debug** [comment]
Emacs 30 adds an [optional argument](https://github.com/emacs-mirror/emacs/blob/emacs-30/lisp/treesit.el#L3679) to choose where to install the files. Would it be possible to do that now?
