### ISSUE TITLE
Major mode substitution (when the grammars are present) isn't consistent

### ISSUE THREAD

**Issue by acid-bong** [renzmann/treesit-auto#89]
(Grammars are already packaged in nixpkgs, so i'm in luck with that, the issue is only about the mode substitution.)

When I'm opening a Rust file (`rust-ts-mode` is built-in, `rust-mode` is absent), the substitution works: it loads up the treesitter-based mode (and, if i'm using `package.el` instead of Nix, asks to install the grammar). Same with languages where the TS-less mode is available (like Python and C).

With Nix files, however, it doesn't work: I install `nix-ts-mode` (`(use-package nix-ts-mode)`), but it doesn't get loaded, neither when `nix-mode` is installed nor when it's not.

I wonder if the reason is that Nix isn't in the recipe list.

**Comment by renzmann** [comment]
> I wonder if the reason is that Nix isn't in the recipe list.

A recipe is the only way for treesit-auto to know what to do for a language (in your case, nix).  Since this issue is about Nix specifically, there are two options:

1. Use the guide from [the README](https://github.com/renzmann/treesit-auto?tab=readme-ov-file#configuring-behavior-for-a-specific-language) on configuring a recipe for your own use
2. Open a PR that adds nix support, following [the CONTRIBUTING guide](https://github.com/renzmann/treesit-auto/blob/main/CONTRIBUTING.org)
